"""Alternate: model Doing, field time_spent - add

Revision ID: 13035836c969
Revises: 9fa3772fc868
Create Date: 2024-05-10 19:59:33.892322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '13035836c969'
down_revision: Union[str, None] = '9fa3772fc868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doing', sa.Column('time_spent', sa.Interval(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doing', 'time_spent')
    # ### end Alembic commands ###
